apiVersion: v1
kind: Service
metadata:
  labels:
    app: techgame
  name: techgame
spec:
  type: NodePort
  ports:
  - name: "techgame-service"
    port: 5000
    targetPort: 80
    nodePort: 31005
  selector:
    app: techgame
