apiVersion: apps/v1
kind: Deployment
metadata:
  name: techgame-deployment
  labels:
    app: techgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techgame
  template:
    metadata:
      labels:
        app: techgame
    spec:
      containers:
          - name: techgame
            image: imranahmad786/techgame:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 5000  # Change from 8080 to 5000
