apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techgame
  name: techgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techgame
  template:
    metadata:
      labels:
        app: techgame
    spec:
      containers:
      - image: shikhardocker/techgame
        name: techgame
        ports:
        - containerPort: 8080
          name: techgame
