apiVersion: v1
kind: Service
metadata:
  name: techgame-ssvc
spec:
  selector:
    app: techgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Change to NodePort if running on Minikube or Bare Metal
