apiVersion: v1
kind: Service
metadata:
  labels:
    app: techgame
  name: techgame
spec:
  type: NodePort
  ports:
  - name: "techgame-service"
    port: 5000
    targetPort: 8080
    nodePort: 31007
  selector:
    app: techgame
  
