apiVersion: v1
kind: Service
metadata:
  name: dotnet-backend-svc
  labels:
    app: dotnet-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"                # Network Load Balancer (for production)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # External access
spec:
  type: LoadBalancer
  selector:
    app: dotnet-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80


===========================================================
Line-by-Line Explanation
1️⃣ apiVersion: v1

Refers to the core Kubernetes API group used for basic resources like Pods, Services, Secrets, and ConfigMaps.

Since Service is a standard resource, it always uses v1.

2️⃣ kind: Service

Defines the type of Kubernetes resource being created — in this case, a Service.

A Service exposes your Pods (backend containers) to other apps or the internet.

It acts as a stable network endpoint (IP or DNS name) even if pod IPs change.

3️⃣ metadata:
metadata:
  name: dotnet-backend-svc
  labels:
    app: dotnet-backend


name: Unique name for the service inside the namespace — used when referencing it internally.

Example: the frontend might call http://dotnet-backend-svc:80 inside the same cluster.

labels: Metadata tags used for identification or grouping resources (like for monitoring, or selectors).

4️⃣ annotations (AWS-specific configuration)
annotations:
  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"


These are EKS (AWS-specific) settings that tell Kubernetes how to create the AWS Load Balancer for your Service.

➤ aws-load-balancer-type: "nlb"

This tells AWS to create a Network Load Balancer (NLB) instead of the default Classic Load Balancer (CLB).

✅ NLB is recommended for production:

Lower latency

Handles millions of requests per second

Better suited for HTTP/HTTPS and gRPC traffic

Supports static IPs per Availability Zone

➤ aws-load-balancer-scheme: "internet-facing"

This makes your load balancer publicly accessible from the internet.

If you want it to be private, for internal VPC access only, you’d use:

service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"

5️⃣ spec:

The spec section defines how the service behaves — how it routes traffic, what ports it exposes, and which pods it targets.

6️⃣ type: LoadBalancer
type: LoadBalancer


This is the service type.

In Kubernetes on AWS, setting type: LoadBalancer automatically:

Provisions an AWS Load Balancer

Assigns it a public DNS name

Exposes the app to the internet

✅ Ideal for production workloads that need to be accessible externally — such as your .NET backend API.

7️⃣ selector:
selector:
  app: dotnet-backend


This connects the Service to your backend Deployment.

It finds all Pods that have the label app: dotnet-backend and routes incoming traffic to them.

So your backend deployment must have:

metadata:
  labels:
    app: dotnet-backend

8️⃣ ports:
ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80


Let’s break that down:

Field	Description
name: http	Optional name to identify this port (useful for monitoring or multi-port services).
protocol: TCP	Specifies TCP protocol for communication (most web apps use TCP).
port: 80	The port exposed by the Service to clients. This is the port your Load Balancer listens on.
targetPort: 80	The port inside the Pod where your container is running (defined in your deployment).

💡 Example:
If your .NET container runs on port 8080, you’d set:

port: 80
targetPort: 8080


So traffic from LoadBalancer:80 → routes to → Pod:8080.

🧠 Real-World Behavior (AWS EKS)

Once you deploy this Service:

kubectl apply -f dotnet-backend-service.yaml


You can check the created load balancer:

kubectl get svc dotnet-backend-svc


You’ll see something like:

NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP                        PORT(S)        AGE
dotnet-backend-svc   LoadBalancer   10.0.45.231    a1b2c3d4e5f6g7.elb.amazonaws.com   80:32145/TCP   1m


✅ The EXTERNAL-IP is your AWS Load Balancer DNS — use this to access your backend from outside:

http://a1b2c3d4e5f6g7.elb.amazonaws.com/
