apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 3500
    protocol: TCP
  type: ClusterIP
  selector:
    role: api


    =======================
    apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
  labels:
    app: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use Network Load Balancer for production (faster & stable)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # External access
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80        # Publicly exposed port
      targetPort: 5000 # Port inside your container




      Detailed Explanation
1. apiVersion, kind, metadata

apiVersion: v1 – Standard API version for a Kubernetes Service.

kind: Service – Defines that this YAML creates a Service.

metadata.name – Name of the Service (referenced by other resources if needed).

namespace – Same as the Deployment namespace (production).

labels – Helps identify and organize this resource.

annotations – Used to configure AWS LoadBalancer properties.

2. Annotations for AWS Load Balancer
Annotation	Description
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"	Uses AWS Network Load Balancer (NLB) — ideal for production (faster, lower latency than CLB).
service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"	Makes it publicly accessible over the internet. Use "internal" for private services.

🧠 Tip:

For HTTP/HTTPS traffic, you can also use "alb" (Application Load Balancer) via AWS Load Balancer Controller.

But "nlb" is simpler and ideal for APIs or TCP-based Node.js apps.

3. spec.type

LoadBalancer – Kubernetes will provision an AWS Load Balancer automatically.

It routes external traffic from the internet to your backend Pods.

4. spec.selector

Matches Pods with the label app: backend — those created by your backend-deployment.yaml.

Ensures traffic is sent only to the correct backend Pods.

5. spec.ports
Field	Description
port: 80	Port exposed to the outside world (Load Balancer).
targetPort: 5000	The internal port inside the Pod (from containerPort in Deployment).
protocol: TCP	Used for standard HTTP/HTTPS API connections.
🏗️ How it Works (in AWS EKS)

When you apply this YAML (kubectl apply -f backend-service.yaml),
EKS will instruct AWS to create an NLB (Network Load Balancer).

The NLB will:

Get a public DNS name (like a1b2c3d4e5f6.elb.amazonaws.com)

Forward incoming requests on port 80 → backend Pods (port 5000)

Kubernetes automatically keeps backend Pods in sync with the load balancer targets.

Production Recommendations:

Add SSL/TLS by using AWS ALB Ingress Controller with HTTPS.

Set up DNS in Route53 to point your domain to the Load Balancer.

Enable PodDisruptionBudget (PDB) to ensure backend availability during node upgrades.

Optionally add HorizontalPodAutoscaler (HPA) to scale backend Pods automatically.


